version: '3'

services:
  database:
    image: postgres:latest
    ports:
      - 15342:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80  
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/
  
  dbeaver:
    image: dbeaver/cloudbeaver
    ports:
      - 8050:8050
    depends_on:
      - database
    volumes:
      - ./config:/home/dbeaver/.config/DBeaverData/